# Generated by Django 4.2.7 on 2025-09-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_size', models.BigIntegerField(verbose_name='파일 크기')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('analysis_time', models.DateTimeField(blank=True, null=True, verbose_name='분석 시간')),
                ('status', models.CharField(choices=[('pending', '분석 대기중'), ('analyzing', '분석 중'), ('completed', '분석 완료'), ('failed', '분석 실패')], default='pending', max_length=20, verbose_name='상태')),
                ('package_name', models.CharField(blank=True, max_length=255, verbose_name='패키지명')),
                ('version_name', models.CharField(blank=True, max_length=100, verbose_name='버전명')),
                ('version_code', models.CharField(blank=True, max_length=50, verbose_name='버전 코드')),
                ('min_sdk', models.CharField(blank=True, max_length=20, verbose_name='최소 SDK')),
                ('target_sdk', models.CharField(blank=True, max_length=20, verbose_name='타겟 SDK')),
                ('permissions', models.JSONField(default=list, verbose_name='권한 목록')),
                ('activities', models.JSONField(default=list, verbose_name='액티비티 목록')),
                ('services', models.JSONField(default=list, verbose_name='서비스 목록')),
                ('receivers', models.JSONField(default=list, verbose_name='리시버 목록')),
                ('api_calls', models.JSONField(default=list, verbose_name='API 호출 목록')),
                ('security_analysis', models.JSONField(default=dict, verbose_name='보안 분석 결과')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
            ],
            options={
                'verbose_name': 'APK 분석',
                'verbose_name_plural': 'APK 분석 목록',
                'ordering': ['-upload_time'],
            },
        ),
    ]
