# Generated by Django 4.2.7 on 2025-10-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkanalysis',
            name='csv_files',
            field=models.JSONField(default=list, verbose_name='CSV 파일 목록'),
        ),
        migrations.AddField(
            model_name='apkanalysis',
            name='csv_output_dir',
            field=models.CharField(blank=True, max_length=500, verbose_name='CSV 출력 디렉토리'),
        ),
    ]
