# Generated by Django 4.2.7 on 2025-10-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_apkanalysis_csv_files_apkanalysis_csv_output_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkanalysis',
            name='comparison',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='권한-처리방침 비교 결과'),
        ),
        migrations.AddField(
            model_name='apkanalysis',
            name='policy_items',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='처리방침 수집 항목'),
        ),
        migrations.AddField(
            model_name='apkanalysis',
            name='policy_items_detail',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='처리방침 항목 상세'),
        ),
    ]
