# Generated by Django 4.2.7 on 2025-10-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_apkanalysis_csv_files_apkanalysis_csv_output_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkanalysis',
            name='policy_labels',
            field=models.JSONField(default=list, verbose_name='처리방침 예측 라벨'),
        ),
    ]
