# Generated by Django 4.2.7 on 2025-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_apkanalysis_policy_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkanalysis',
            name='policy_sentence_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
