# Generated by Django 4.2.7 on 2025-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_apkanalysis_comparison_apkanalysis_policy_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkanalysis',
            name='policy_labels',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='처리방침 예측 라벨'),
        ),
        migrations.AddField(
            model_name='apkanalysis',
            name='policy_sentence_labels',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='문장 단위 라벨'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='activities',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='액티비티 목록'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='api_calls',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='API 호출 목록'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='comparison',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='APK × 정책 비교'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='csv_files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='CSV 파일 목록'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='csv_output_dir',
            field=models.TextField(blank=True, null=True, verbose_name='CSV 출력 디렉토리'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='오류 메시지'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='파일 크기'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='min_sdk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='최소 SDK'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='패키지명'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='권한 목록'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='policy_items',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='정책 항목 요약'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='policy_items_detail',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='정책 항목 상세'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='receivers',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='리시버 목록'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='security_analysis',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='보안 분석 결과'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='services',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='서비스 목록'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='target_sdk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='타겟 SDK'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='version_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='버전 코드'),
        ),
        migrations.AlterField(
            model_name='apkanalysis',
            name='version_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='버전명'),
        ),
        migrations.AddIndex(
            model_name='apkanalysis',
            index=models.Index(fields=['file_name'], name='analyzer_ap_file_na_5c6d16_idx'),
        ),
        migrations.AddIndex(
            model_name='apkanalysis',
            index=models.Index(fields=['package_name'], name='analyzer_ap_package_4b8b70_idx'),
        ),
        migrations.AddIndex(
            model_name='apkanalysis',
            index=models.Index(fields=['status'], name='analyzer_ap_status_e0217b_idx'),
        ),
    ]
